
project_id = "bupbikzhhouzlwzpkwxp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.process-entry]
verify_jwt = true

[functions.analyze-category]
verify_jwt = true

[functions.analyze-url]
verify_jwt = true

[functions.process-chat]
verify_jwt = true

[functions.research-content]
verify_jwt = true
