
project_id = "bupbikzhhouzlwzpkwxp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[[functions]]
[functions.process-entry]
verify_jwt = true

[[functions]]
[functions.analyze-category]
verify_jwt = true
